kind: ENC[AES256_GCM,data:8p5blggK,iv:LFaUovabrAZEhpp/bnftZbhdOjtyUwmN0uwCcz+TPTw=,tag:8BXG3kbVz7/D1ktvgn3Ceg==,type:str]
ansible_user: ENC[AES256_GCM,data:O7zlaZs=,iv:2AF+qTFXoa59gbMd4SmzWiSqlhiMoouT+O/ZzkrZB4U=,tag:A6DxEFYwvfk7WlA6MqrUhA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:8WjAaX22ZlN1lsrwBTC+Xw==,iv:VBR2f5M4N9wySDktQiPj1ZlX9ruMo+4ITAJT4Sia0NU=,tag:sfc+tkwi785pMrj2hgEw0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1czw3wv7cwhm6swsj5v9uv4q7truevhvqszkgt34pe0p9jknn8e3slagdzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6b1AzeGNCSUlQKy9na2Z0
            TDBrazM1SDNkMTdEYlpyWFRDVkUyNXNldVE0CmxjUzAzeDhacThwaW9CbHVqYkxE
            ellnSzlFVUE0TmU5WDJDNlUzUkNDYU0KLS0tIHc5N0hvbTlMRDBsdy9BbGlLNGlF
            MWhjVDVGRzBSM3VzU3h2NzRidU5HUGcKGxbdfQSovV8qlyVwe5r+liktsVmDzfuM
            0sG0tXtT0XOeFst4utSEi+6C/Wwhxk0TYRTuhWA/z+Y9A1yjXgZ4UQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-05T08:09:04Z"
    mac: ENC[AES256_GCM,data:5l4HDaN84aefEl7JdjLvMlajD7OIh6/2L8yiL4ZAu+fjdz7F5U88XZOFG73/drWhYVOnOtBc4kwfk8oGuxZvX52MfJCiPrl+ZCrYFLCNBi3pypdBYMV2Ki+Q/p9N7jIqU/gU7211YVOFfYhn56WTgC6iJj81KOQfduddY6kfNMM=,iv:VmVt3ID1DBDOCOt+Tc4RFh5pTbPc0AGNqkrOCHWrVDw=,tag:yU2DmgCnBOe8GEVcirt9QQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
