---
all:
  children:
    provision:
      hosts:
        pve:
          ansible_host: 192.168.50.10
    kubernetes:
      children:
        master:
          hosts:
            k3s-00:
              ansible_host: 192.168.50.33
        worker:
          hosts:
            k3s-01:
              ansible_host: 192.168.50.34
            k3s-02:
              ansible_host: 192.168.50.35
