---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Amsterdam"
  K8S_GATEWAY_ADDR: ""
  INGRESS_NGINX_ADDR: "192.168.50.31"
  KUBE_VIP_ADDR: "192.168.50.32"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
