apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ""
    credentials.json: ENC[AES256_GCM,data:LRAREOhoonP4aOig68tfL7SY9dw63cbIhMhzgsZpaH2ZwmzfVQdBNKUyYjepwk/ZyvM4Nu1Rp/CAJMTDfXIP,iv:9C7J1eb9A+spbQkqF4v2fOd2/wbQxGE+3ddVGHCBJ+M=,tag:YFZhR8SfuAXY/YLSxvWLeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1czw3wv7cwhm6swsj5v9uv4q7truevhvqszkgt34pe0p9jknn8e3slagdzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VWtaV1A3K2piVVVCUUpT
            Nk9jRUsyNUFZTzUrbmE2aDRUMi8wNnhob1VVCjdmeFYrYU5VT2RjTWVoUU1uUHNu
            eEZMNHFzU0RoVGN6OEozRDlBaWlDOVkKLS0tIFBVQmd2cTIwVmxwSW94TlpyV3F1
            aUZITm1DWkxJUlpGbFNMT01jaC9ZQVEKw/C9YWpqxMBOuAkv94ONTxg7kD5107dn
            NfEluFHRQi6DwXdiGaEZwTr7QbI4D80XjMNeU3t4/b06Dog1fZXu5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-05T08:09:04Z"
    mac: ENC[AES256_GCM,data:JiJnYmcjUbinYnDI2UvUbLMvVVMpPrdQsDe7sqtQDzcjOlREu4QydeRVTNnYePNaMtmzZ0x+LweUbqgvaIYoMUe8xLHq9Il2EJmNxBejJr5+lPWrdoXgW57g2N6NGV5RJ6epAJx4ctg39H2IDavT6Expm/b4gE/cPwYgI8oeYtY=,iv:7QNZCWU8PLGIuss/tJqwNGYOYMn/4oNQKMJSOVFNgbA=,tag:yoY4a3jysVM1zOmLCvfk7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
