apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ""
    credentials.json: ENC[AES256_GCM,data:ooWKLv4L9GVrmTRbQZ8Oi+GwdmgJPAdIvJ1J5i7feuRFfe+pwGNRA7sAuEEKZtI12KnEbJMDyusIEYO9mQVD,iv:Hf03kYshjO1g7yDO27f7sylHW+kvLVj7PfVYsXQB5Ac=,tag:pxT3NQyXdru4ubNiJTHaxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1czw3wv7cwhm6swsj5v9uv4q7truevhvqszkgt34pe0p9jknn8e3slagdzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeElaK3RpTTRlak5aNGJD
            TzJydjVDY1hlWmJHcS9lakxsYk1CMFlUa0NBCmpKS3N0YlVJUXJCRmx5Y1pndjBm
            YzdCVWRqYURhZ1VaRDZZYlBVdkJWT0kKLS0tIE8xczA1ZXhoY3luZFlFUTliR011
            RldYVEVPUStuTXc4OCtVYTQyUDFaUkkKhWlWxvxivxqo7qIJymqaeZOIGQK1Qc+S
            d/jurRl5HSJka5NH8zqkMdMZQXdIg5T4WYrkDZo8qDAkQiOFFbgzUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-04T20:48:14Z"
    mac: ENC[AES256_GCM,data:W9eP840RPh7iBhah3f/HJx/hd6kcLOirVqatLqoy7mbEAG6SvFRXQh1fkP2nX2ahNAwOKANToJ00q07qESDlprWnrnG3O5pJxH8fgkKAzHsqBVRRFGdcvE/uRw43usyXeSaYN8hma1GAl2BFaSalcmPYVyOX1FzfYoqneuVbslM=,iv:5z3l41dBO5wKhn6U0izXyoLFBMBYui9yRquV2Dgbnb8=,tag:QaCs5fNjVGtonABUs4Eb6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
